histologiaonline/app/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', Index.as_view(), name='index'),  # Rota para a página inicial
    path('registro/', UsuarioRegisterView.as_view(), name='registro'),  # Rota para registro
    path('senha_reset/', SenhaResetView.as_view(), name='senha_reset'),
    path('login/', UsuarioLoginView.as_view(), name='login'),  # Rota para login
    path('logout/', UsuarioLogoutView.as_view(), name='logout'),  # Rota para logout
    path('suporte/', SuporteCreateView.as_view(), name='suporte'),
    path('conteudos/', ConteudosView.as_view(), name='conteudos'),
    path('chat/', GerenciarChatView.as_view(), name='chat'),
    path('atividades/', AtividadesView.as_view(), name='atividades'),
    path('gabarito/', GabaritoView.as_view(), name='gabarito'),
    path('bibliografia/', BibliografiaView.as_view(), name='bibliografia'),
]

histologiaonline/config/urls.py
from django.contrib import admin
from django.urls import path, include  

urlpatterns = [
    path('admin/', admin.site.urls), 
    path('', include('app.urls')),  
]

histologiaonline/app/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class Usuario(AbstractUser):
    Aluno = 'aluno'
    Professor = 'professor'

    CARGO_CHOICES = [
        (Aluno, 'Aluno'),
        (Professor, 'Professor'),
    ]

    data_nascimento = models.DateField(verbose_name="Data de Nascimento", blank=True, null=True)
    cargo = models.CharField(max_length=50, choices=CARGO_CHOICES, default=Aluno, verbose_name="Cargo", blank=True, null=True)
    chat = models.ForeignKey('Chat', on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

    def save(self, *args, **kwargs):
        # Se o cargo for 'Professor', o usuário será superusuário
        if self.cargo == self.Professor:
            self.is_superuser = True
            self.is_staff = True
        else:
            self.is_superuser = False
            self.is_staff = False

        super().save(*args, **kwargs)

class Bibliografia(models.Model):
    titulo = models.CharField(max_length=255)
    autor = models.CharField(max_length=100)
    ano_publicacao = models.IntegerField()
    editora = models.CharField(max_length=100, blank=True, null=True)
    link = models.URLField(blank=True, null=True)

    def __str__(self):
        return self.titulo

class Conteudos(models.Model):
    nome = models.CharField(max_length=255)
    data_publi_autor = models.DateField()
    curiosidades = models.TextField(blank=True, null=True)
    tema_especifico = models.CharField(max_length=255, blank=True, null=True)
    bibliografia = models.ForeignKey(Bibliografia, on_delete=models.CASCADE, related_name='conteudos')


    def __str__(self):
        # Retorna o nome do conteúdo e o autor da bibliografia
        return f"{self.nome} - Autor da Bibliografia: {self.bibliografia.autor if self.bibliografia else 'N/A'}"
    
class Chat(models.Model):
    assunto = models.CharField(max_length=255)
    mensagem = models.TextField()
    resposta = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.assunto

class Suporte(models.Model):
    problemas = models.TextField()
    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE)

    def __str__(self):
        return f"Suporte {self.id} - {self.usuario}"

class Quiz(models.Model):
    titulo = models.CharField(max_length=255)  # Título do quiz
    pergunta = models.CharField(max_length=255)  # Texto da pergunta
   
    def __str__(self):
        return self.titulo

class Resposta(models.Model):
    Quiz = models.ForeignKey( Quiz , on_delete=models.CASCADE, related_name='respostas')  # Pergunta relacionada
    texto = models.CharField(max_length=255)  # Texto da resposta
    ordem = models.IntegerField()  # Ordem de exibição
    correta = models.BooleanField(default=False)  # Indica se a resposta é correta

    def __str__(self):
        return self.texto

class TentativaQuiz(models.Model):
    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE)  # Usuário que fez a tentativa
    data_tentativa = models.DateTimeField(auto_now_add=True)  # Data da tentativa
    pontuacao = models.IntegerField()  # Pontuação obtida na tentativa
    total_perguntas = models.IntegerField()  # Total de perguntas do quiz

    def __str__(self):
        return f"Tentativa de {self.usuario} em {self.data_tentativa} - Pontuação: {self.pontuacao}"

histologiaonline/app/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import *
from django.contrib.auth.models import User


class UsuarioCreationForm(UserCreationForm):
    nascimento = forms.DateField(
        widget=forms.DateInput(attrs={'type': 'date'}),
        label='Data de Nascimento'
    )  # Campo para a data de nascimento com widget para o seletor de data

    class Meta:
        model = Usuario
        fields = ['username', 'first_name', 'last_name', 'email', 'nascimento', 'cargo', 'password1', 'password2']  # Adicionando os campos necessários

    
class SuporteForm(forms.ModelForm):
    class Meta:
        model = Suporte
        fields = ['problemas']  # Não inclua 'usuario' aqui

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super(SuporteForm, self).__init__(*args, **kwargs)

    def save(self, commit=True):
        suporte = super(SuporteForm, self).save(commit=False)
        if self.user is not None:
            suporte.usuario = self.user  # Atribui o usuário
        if commit:
            suporte.save()
        return suporte
    
class ChatForm(forms.ModelForm):
    class Meta:
        model = Chat
        fields = ['assunto', 'mensagem']


class PasswordResetForm(forms.Form):
    email = forms.EmailField(label='E-mail', max_length=254)
    new_password = forms.CharField(widget=forms.PasswordInput, label='Nova Senha')

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if not Usuario.objects.filter(email=email).exists():
            raise forms.ValidationError("O e-mail não está registrado.")
        return email

histologiaonline/app/templates/autenticacao/login.html
{% load static %} <!-- Carregar o static para uso -->

<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Noto+Sans:wgth@400;700&display=swap');

        body {
            margin: 0;
            font-family: 'Noto Sans', sans-serif;
            overflow: hidden;
        }

        body * {
            box-sizing: border-box;
        }

        .main-login {
            width: 100vw;
            height: 100vh;
            background: #201b2c;
            display: flex;
            justify-content: center;
            align-items: center;
        }

        .left-login {
            width: 50vw;
            height: 100vh;
            display: flex;
            justify-content: center;
            align-items: center;
            flex-direction: column;
        }

        .left-login>h1 {
            font-size: 3vw;
            color: #77ffc0;
        }

        .left-login-image {
            width: 35vw;
        }

        .right-login {
            width: 50vw;
            height: 100vh;
            display: flex;
            justify-content: center;
            align-items: center;
        }

        .card-login {
            width: 60%;
            display: flex;
            justify-content: center;
            align-items: center;
            flex-direction: column;
            padding: 30px 35px;
            background: #2f2841;
            border-radius: 20px;
            box-shadow: 0px 10px 40px #00000056;
        }

        .card-login>h1 {
            color: #00ff88;
            font-weight: 800;
            margin: 0;
        }

        .textfield {
            width: 100%;
            display: flex;
            flex-direction: column;
            align-items: flex-start;
            justify-content: center;
            margin: 10px 0px;
            margin-bottom: 15px;
        }

        .textfield>input {
            width: 100%;
            border: none;
            border-radius: 10px;
            padding: 15px;
            background: #514869;
            color: #f0ffffde;
            font-size: 12pt;
            box-shadow: 0px 10px 40px #00000056;
            outline: none;
            box-sizing: border-box;
        }

        .textfield>label {
            color: #f0ffffde;
            margin-bottom: 10px;
        }

        .textfield>input::placeholder {
            color: #f0ffff94;
        }

        .btn-login {
            width: 100%;
            padding: 16px 0px;
            margin-bottom: 15px;
            border: none;
            border-radius: 8px;
            outline: none;
            text-transform: uppercase;
            font-weight: 800;
            letter-spacing: 4px;
            color: #2b134b;
            background: #00ff88;
            cursor: pointer;
            box-shadow: 0px 10px 40px -12px #00ff8052;
        }

        .btn-cadastro {
            width: 100%;
            padding: 16px 0px;
            border: none;
            border-radius: 8px;
            outline: none;
            text-transform: uppercase;
            font-weight: 800;
            letter-spacing: 4px;
            color: #2b134b;
            background: #4efcb5;
            cursor: pointer;
            box-shadow: 0px 10px 40px -12px #00ff8052;
        }
        .btn-senha_reset {
            width: 100%;
            padding: 16px 0px;
            margin-top: 15px;
            border: none;
            border-radius: 8px;
            outline: none;
            text-transform: uppercase;
            font-weight: 800;
            letter-spacing: 4px;
            color: #2b134b;
            background: #fff;
            cursor: pointer;
            box-shadow: 0px 10px 40px -12px #00ff8052;
        }
        @media only screen and (max-width: 950px) {
            .card-login {
                width: 85%;
            }
        }

        @media only screen and (max-width: 600px) {
            .main-login {
                flex-direction: column;
            }

            .left-login>h1 {
                display: none;
            }

            .left-login {
                width: 100%;
                height: auto;
            }

            .right-login {
                width: 100%;
                height: auto;
            }

            .left-login-image {
                width: 50vw;
            }

            .card-login {
                width: 90%;
            }
        }

        .password-container {
            position: relative;
            width: 100%;
            /* Garante que ocupe todo o espaço disponível */
        }

        #senha {
            width: 100%;
            /* Preenche toda a largura do container */
            padding-right: 40px;
            /* Espaço para o ícone */
            border: none;
            border-radius: 10px;
            padding: 15px;
            background: #514869;
            color: #f0ffffde;
            font-size: 12pt;
            box-shadow: 0px 10px 40px #00000056;
            outline: none;
            box-sizing: border-box;
        }

        .toggle-password {
            position: absolute;
            right: 10px;
            /* Posiciona o ícone no canto direito */
            top: 50%;
            /* Centraliza verticalmente */
            transform: translateY(-50%);
            cursor: pointer;
        }

        .toggle-password i {
            font-size: 20px;
            color: #f0ffffde;
            /* Cor do ícone */
        }
          /* Estilos para as mensagens */
    .messages-container {
        margin-top: 20px;
    }

    .alert {
        color: white; /* Texto branco */
        background-color: #333; /* Cor de fundo escura para contrastar */
        border: 1px solid #444;
    }

    /* Definindo um tempo de fade-out (transição suave de ocultação) */
    .alert {
        opacity: 1;
        transition: opacity 0.5s ease-out;
    }

    .alert.hide {
        opacity: 0;
    }
    </style>
</head>

<body>
    <div class="main-login">
        <div class="left-login">
            <h1>Faça login<br>Entre para o nosso time de Estudos!</h1>
            <img src="{% static 'cerebro.svg' %}" class="left-login-image" alt="Cérebro animação">
            <!-- Corrigido com static -->
        </div>
        <div class="right-login">
            <div class="card-login">
                <h1>LOGIN</h1>
                {% if messages %}
                <div class="messages-container">
                    {% for message in messages %}
                    <div class="alert alert-danger" role="alert">
                        {{ message }}
                    </div>
                    {% endfor %}
                </div>
                {% endif %}
                <form method="POST">
                    {% csrf_token %}
                    <div class="textfield">
                        <label for="usuario">Usuário</label>
                        <input type="text" name="username" placeholder="Usuário">
                    </div>
                    <div class="textfield">
                        <label for="senha">Senha</label>
                        <div class="password-container">
                            <input type="password" name="password" id="senha" placeholder="Senha">
                            <span id="toggle-password" class="toggle-password">
                                <i class="fas fa-eye" id="eye-icon" style="color: #201b2c;"></i>
                            </span>
                        </div>
                    </div>
                    <button type="submit" class="btn-login">Login</button>
                    <a href="{% url 'registro' %}"><button type="button" class="btn-cadastro">Cadastre-se</button></a>
                    
                    <a href="{% url 'senha_reset' %}"><button type="button" class="btn-senha_reset">Resetar Senha</button></a>
                </form>
            </div>
        </div>
    </div>
</body>

<script>
    const togglePassword = document.querySelector('#toggle-password');
    const passwordField = document.querySelector('#senha');
    const eyeIcon = document.querySelector('#eye-icon');

    togglePassword.addEventListener('click', function () {
        // Alterna o tipo de senha entre "text" e "password"
        const type = passwordField.getAttribute('type') === 'password' ? 'text' : 'password';
        passwordField.setAttribute('type', type);

        // Alterna o ícone do olho entre aberto e fechado
        eyeIcon.classList.toggle('fa-eye');
        eyeIcon.classList.toggle('fa-eye-slash');
    });
    document.addEventListener('DOMContentLoaded', function () {
            // Seleciona todas as mensagens
            const messages = document.querySelectorAll('.messages-container');

            messages.forEach(function (msg) {
                // Exibe a mensagem por 5 segundos (5000 milissegundos)
                setTimeout(function () {
                    msg.style.display = 'none';  // Remove a mensagem
                }, 5000);
            });
        });
</script>

</html>

histologiaonline/app/templates/autenticacao/registro.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cadastro de Usuário</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Noto+Sans:wgth@400;700&display=swap');

        body {
            margin: 0;
            font-family: 'Noto Sans', sans-serif;
            overflow: hidden;
        }

        body * {
            box-sizing: border-box;
        }

        .main-login {
            width: 100vw;
            height: 100vh;
            background: #201b2c;
            display: flex;
            justify-content: center;
            align-items: center;
        }

        .left-login {
            width: 50vw;
            height: 100vh;
            display: flex;
            justify-content: center;
            align-items: center;
            flex-direction: column;
        }

        .left-login>h1 {
            font-size: 3vw;
            color: #77ffc0;
        }

        .left-login-image {
            width: 35vw;
        }

        .right-login {
            width: 50vw;
            height: 100vh;
            display: flex;
            justify-content: center;
            align-items: center;
        }

        .card-login {
            width: 90%;
            display: flex;
            justify-content: center;
            align-items: center;
            flex-direction: column;
            padding: 30px 35px;
            background: #2f2841;
            border-radius: 20px;
            box-shadow: 0px 10px 40px #00000056;
        }

        .card-login>h3 {
            color: #00ff88;
            font-weight: 800;
            margin: 0;
        }

        .textfield {
            width: 100%;
            display: flex;
            flex-direction: column;
            align-items: flex-start;
            justify-content: center;
            margin: 10px 0px;
            margin-bottom: 15px;
        }

        .textfield>input,
        .textfield>select {
            width: 100%;
            border: none;
            border-radius: 10px;
            padding: 15px;
            background: #514869;
            color: #f0ffffde;
            font-size: 12pt;
            box-shadow: 0px 10px 40px #00000056;
            outline: none;
            box-sizing: border-box;
        }

        .textfield>label {
            color: #f0ffffde;
            margin-bottom: 10px;
        }

        .textfield>input::placeholder,
        .textfield>select::placeholder {
            color: #f0ffff94;
        }

        .btn-login {
            width: 100%;
            padding: 16px 0px;
            margin-bottom: 15px;
            border: none;
            border-radius: 8px;
            outline: none;
            text-transform: uppercase;
            font-weight: 800;
            letter-spacing: 4px;
            color: #2b134b;
            background: #00ff88;
            cursor: pointer;
            box-shadow: 0px 10px 40px -12px #00ff8052;
        }

        .btn-cadastro {
            width: 100%;
            padding: 16px 0px;
            border: none;
            border-radius: 8px;
            outline: none;
            text-transform: uppercase;
            font-weight: 800;
            letter-spacing: 4px;
            color: #2b134b;
            background: #4efcb5;
            cursor: pointer;
            box-shadow: 0px 10px 40px -12px #00ff8052;
        }

        @media only screen and (max-width: 950px) {
            .card-login {
                width: 85%;
            }
        }

        @media only screen and (max-width: 600px) {
            .main-login {
                flex-direction: column;
            }

            .left-login>h3 {
                display: none;
            }

            .left-login {
                width: 100%;
                height: auto;
            }

            .right-login {
                width: 100%;
                height: auto;
            }

            .left-login-image {
                width: 50vw;
            }

            .card-login {
                width: 90%;
            }
        }

        /* Estilo de duas colunas */
        .form-row {
            display: flex;
            flex-wrap: wrap;
            justify-content: space-between;
            width: 100%;
        }

        .form-row .textfield {
            width: 48%;
        }

        .form-row .textfield:nth-child(odd) {
            margin-right: 4%;
        }

        .password-container {
            position: relative;
            width: 100%;
        }

        .password-container input {
            width: 100%;
            padding: 15px;
            background: #514869;
            color: #f0ffffde;
            font-size: 12pt;
            border: none;
            border-radius: 10px;
            box-shadow: 0px 10px 40px #00000056;
            outline: none;
            box-sizing: border-box;
        }

        .toggle-password {
            position: absolute;
            right: 10px;
            top: 50%;
            transform: translateY(-50%);
            background: none;
            /* Removendo o fundo */
            border: none;
            /* Removendo borda */
            cursor: pointer;
        }

        .toggle-password i {
            font-size: 20px;
            color: #FFF;
            /* Cor do ícone */
        }

        tyle>

        /* Estilos para as mensagens */
        .messages-container {
            margin-top: 20px;
        }

        .alert {
            color: white;
            /* Texto branco */
            background-color: #333;
            /* Cor de fundo escura para contrastar */
            border: 1px solid #444;
        }

        /* Definindo um tempo de fade-out (transição suave de ocultação) */
        .alert {
            opacity: 1;
            transition: opacity 0.5s ease-out;
        }

        .alert.hide {
            opacity: 0;
        }
    </style>
</head>

<body>
    <div class="main-login">
        <div class="left-login">
            <h1>Crie sua Conta<br>Comece a usar nosso sistema!</h1>
            <img src="{% static 'cerebro.svg' %}" class="left-login-image" alt="Cérebro animação">
        </div>
        <div class="right-login">
            <div class="card-login">

                <h3>Cadastro de Usuário</h3>
                {% if messages %}
                <div class="messages-container">
                    {% for message in messages %}
                    <div class="alert alert-danger" role="alert">
                        {{ message }}
                    </div>
                    {% endfor %}
                </div>
                {% endif %}
                <form method="POST">
                    {% csrf_token %}

                    <!-- Formulário em duas colunas -->
                    <div class="form-row">
                        <div class="textfield">
                            <label for="id_username">Nome de Usuário</label>
                            {{ form.username }}
                        </div>

                        <div class="textfield">
                            <label for="id_first_name">Primeiro Nome</label>
                            {{ form.first_name }}
                        </div>

                        <div class="textfield">
                            <label for="id_last_name">Sobrenome</label>
                            {{ form.last_name }}
                        </div>

                        <div class="textfield">
                            <label for="id_email">E-mail</label>
                            {{ form.email }}
                        </div>
                    </div>

                    <div class="form-row">
                        <div class="textfield">
                            <label for="id_nascimento">Data de Nascimento</label>
                            {{ form.nascimento }}
                        </div>

                        <div class="textfield">
                            <label for="id_cargo">Cargo</label>
                            {{ form.cargo }}
                        </div>

                        <div class="textfield">
                            <label for="id_password1">Senha</label>
                            <div class="password-container">
                                {{ form.password1 }}
                                <button type="button" class="toggle-password" onclick="togglePassword('id_password1')">
                                    <i class="fas fa-eye" id="eye-icon"></i>
                                </button>
                            </div>

                        </div>

                        <div class="textfield">
                            <label for="id_password1">Senha</label>
                            <div class="password-container">
                                {{ form.password2 }}
                                <button type="button" class="toggle-password" onclick="togglePassword('id_password2')">
                                    <i class="fas fa-eye" id="eye-icon"></i>
                                </button>
                            </div>

                        </div>
                    </div>



                    <button type="submit" class="btn-login">Cadastrar</button>
                    <a href="{% url 'login' %}"><button type="button" class="btn-cadastro">Voltar ao Login</button></a>
                </form>
            </div>
        </div>
    </div>

    <script>


        // Função para alternar visibilidade da senha
        function togglePassword(id) {
            var passwordField = document.getElementById(id);
            var eyeIcon = document.getElementById('eye-icon');
            if (passwordField.type === "password") {
                passwordField.type = "text";
                eyeIcon.classList.remove("fa-eye");
                eyeIcon.classList.add("fa-eye-slash");
            } else {
                passwordField.type = "password";
                eyeIcon.classList.remove("fa-eye-slash");
                eyeIcon.classList.add("fa-eye");
            }
        }
        document.addEventListener('DOMContentLoaded', function () {
            // Seleciona todas as mensagens
            const messages = document.querySelectorAll('.messages-container');

            messages.forEach(function (msg) {
                // Exibe a mensagem por 5 segundos (5000 milissegundos)
                setTimeout(function () {
                    msg.style.display = 'none';  // Remove a mensagem
                }, 5000);
            });
        });
    </script>
</body>

</html>